const path = require("path");
const { walk } = require("../repo/files");

const SKIP = new Set([".git", ".gradle", "build", "node_modules", ".idea", ".vscode", "run", "runs", "logs", "crash-reports", "out", "tmp", "temp"]);
const DOCS = ["CURSEFORGE.md", "MODRINTH.md", "plan.md"];

const publishable = (file) => {
  const name = path.basename(file).toLowerCase();
  return ![".env", ".local", ".tmp"].some((suffix) => name.endsWith(suffix)) && !name.includes("workspace");
};

const folderSource = async (repoPath, folder) => {
  const base = path.join(repoPath, folder);
  const files = await walk(base, () => true, SKIP);
  return files.filter(publishable).map((source) => ({ source, relative: path.relative(base, source) }));
};

const mainSource = async (repoPath) => {
  const { access } = require("fs/promises");
  const items = [];
  for (const name of DOCS) try { await access(path.join(repoPath, name)); items.push({ source: path.join(repoPath, name), relative: name }); } catch {}
  return items;
};

const gitignoreContent = () => [
  "# Generated by Project Workspace Center", "build/", ".gradle/", "run/", "runs/", "logs/", "crash-reports/",
  "node_modules/", ".idea/", ".vscode/", "out/", "tmp/", "temp/", "*.log", ".env", "scripts/.workspace-center/"
].join("\n");

module.exports = { DOCS, folderSource, mainSource, gitignoreContent };
